plugins {
    id 'java'
    id 'maven-publish'
    id 'com.google.protobuf' version '0.9.6'
}

group = 'io.pitlens'

version = providers.gradleProperty('version')
        .getOrElse('0-SNAPSHOT')

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.protobuf:protobuf-java:4.36.2'

    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:4.32.1'
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            groupId = project.group
            artifactId = 'pitlens-contracts'
            version = project.version
        }
    }

    repositories {
        maven {
            name = 'GitHubPackages'
            url = uri('https://maven.pkg.github.com/pitlens/pitlens-contracts')

            credentials {
                username = project.findProperty('gpr.user')
                        ?: System.getenv('GITHUB_ACTOR')

                password = project.findProperty('gpr.key')
                        ?: System.getenv('GITHUB_TOKEN')
            }
        }
    }
}

test {
    useJUnitPlatform()
}

tasks.register('printVersion') {
    doLast {
        println ""
        println "PitLens Contracts version: ${project.version}"
        println ""
    }
}

tasks.named('build') {
    dependsOn 'printVersion'
}
